# Generated by Django 4.0.4 on 2022-05-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('nombre_en_stock', models.IntegerField()),
                ('resume', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
