# Generated by Django 4.0.4 on 2022-05-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSNCF', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livre',
            new_name='train',
        ),
    ]
