# Generated by Django 4.0.4 on 2022-05-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSNCF', '0002_rename_livre_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
            ],
        ),
    ]
