# Generated by Django 4.0.4 on 2022-05-15 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appSNCF', '0004_alter_train_marque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='marque',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appSNCF.marque'),
        ),
    ]
